#!/usr/bin/env bash
# Install nginx on my web01 server
# Nginx should be listening on port 80
apt-get update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
