#!/usr/bin/env bash
#redirecting to a different location
apt-get update
sudo apt-get install -y nginx
sudo touch /var/www/html/notfound_404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/notfound_404.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /var/www/html;
    index  index.html index.htm index.nginx-debian.html;
    location /redirect_me {
        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
    }
    error_page 404 /notfound_404.html;
    location /notfound_404 {
    	root /var/www/html;
	internal;
	}
}" | sudo tee /etc/nginx/sites-available/default
sudo service nginx restart
