#!/usr/bin/env bash
# This script is daiplaying a text 10 times using while loop
text="Best School"
i=1
while [ $i -lt 10 ]; do
    if [[ $i == 9 ]]; then
	echo "Hi"
    fi
    ((i += 1))
    echo "$text"
done
