#!/usr/bin/env bash
# This script is daiplaying a text 10 times using while loop
count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
