#!/usr/bin/env bash
# display the content of the current directory
# in list format
# Where only the part of the name after the first dash is displayed
items=$(ls)
for i in $items; do
    echo "$i" | cut -d '-' -f2
done
